config/routes.rb
Copycopter::Application.routes.draw do
  namespace :api do
    namespace :v2 do
      resources :projects, :only => [] do
        resources :deploys, :only => [:create]
        resources :draft_blurbs, :only => [:create, :index]
        resources :published_blurbs, :only => [:index]
      end
    end
  end

  resources :projects, :only => [:index, :show] do
    resources :blurbs, :only => [:destroy]
    resources :locales, :only => [:new]
  end

  resources :localizations, :only => [] do
    resources :versions, :only => [:new, :create]
  end

  root :to => 'projects#index'
end

app/models/project.rb
require 'extensions/string'

class Project < ActiveRecord::Base
  # Attributes
  attr_accessible :name, :password, :username

  # Associatons
  has_many :blurbs
  belongs_to :draft_cache, class_name: 'TextCache', dependent: :destroy
  has_many :locales, dependent: :delete_all
  has_many :localizations, through: :blurbs
  belongs_to :published_cache, class_name: 'TextCache', dependent: :destroy

  # Validations
  validates_presence_of :api_key, :name, :password, :username
  validates_uniqueness_of :api_key

  # Callbacks
  before_validation :generate_api_key, on: :create
  before_create :create_caches
  after_create :create_english_locale
  after_destroy :delete_localizations_and_blurbs

  def self.archived
    where archived: true
  end

  def self.active
    where archived: false
  end

  def active?
    !archived
  end

  def self.by_name
    order 'projects.name'
  end

  def create_defaults(hash)
    DefaultCreator.new(self, hash).create
  end

  def default_locale
    locales.first_enabled
  end

  def deploy!
    localizations.publish
    update_caches
  end

  def draft_json(options = { hierarchy: false })
    if options[:hierarchy]
      draft_cache.hierarchichal_data
    else
      draft_cache.data
    end
  end

  def etag
    [updated_at.to_i.to_s, updated_at.usec.to_s].join
  end

  def locale(locale_id = nil)
    if locale_id
      locales.find locale_id
    else
      default_locale
    end
  end

  def lock_key_for_creating_defaults
    "project-#{id}-create-defaults"
  end

  def published_json(options = { hierarchy: false })
    if options[:hierarchy]
      published_cache.hierarchichal_data
    else
      published_cache.data
    end
  end

  def self.regenerate_caches
    find_each do |project|
      project.update_caches
    end
  end

  def update_caches
    draft_cache.update_attributes!(generate_json(:draft_content))
    published_cache.update_attributes!(generate_json(:published_content))
    touch
  end

  private

  def create_caches
    self.draft_cache = TextCache.create!(:data => '{}')
    self.published_cache = TextCache.create!(:data => '{}')
  end

  def create_english_locale
    locales.create! key: 'en'
  end

  def delete_localizations_and_blurbs
    transaction do
      blurb_ids = Blurb.select('id').where(project_id: self.id).map(&:id)
      Localization.where(blurb_id: blurb_ids).delete_all
      Blurb.where(project_id: self.id).delete_all
    end
  end

  def generate_api_key
    self.api_key = SecureRandom.hex(24)
  end

  def generate_json(content)
    blurbs_hash = blurbs.to_hash(content)
    blurbs_hash[:data] = Yajl::Encoder.encode blurbs_hash[:data]
    blurbs_hash[:hierarchichal_data] = Yajl::Encoder.encode blurbs_hash[:hierarchichal_data]
    blurbs_hash
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize, only: [:show]

  def index
    @projects = Project.active
  end

  def show
    @project = Project.find(params[:id])
    @locale = @project.locale(params[:locale_id])

    if stale? etag: @project.etag
      @localizations = @project.localizations.in_locale_with_blurb(@locale)
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_copycopter.rb.erb
CopycopterClient.configure do |config|
  config.api_key = '<%= project.api_key %>'
  config.host = '<%= request.host %>'
end

app/views/projects/_installation_instructions.html.erb
<div class='installation_instructions'>
  <h3>Setting up your Rails app</h3>

  <ol>
    <li>
      Add the copycopter_client gem to your bundler Gemfile:
      <pre>gem 'copycopter_client', '~> 2.0.1'</pre>
    </li>

    <li>
      Put this in your config/initializers/copycopter.rb:
      <% self.formats = [:html, :rb] %>
      <pre><%= render :partial => 'projects/copycopter', :locals => {:project => project} %></pre>
    </li>
  </ol>
</div>

app/views/projects/index.html.erb
<% content_for :header do %>
  <h2><strong>Projects</strong></h2>
<% end %>

<ul class='projects'>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/show.html.erb
<% content_for :title, 'Blurbs' %>

<% content_for :locales do %>
  <% @project.locales.enabled_in_order.each do |locale| -%>
    <li>
      <%= link_to locale.key, project_path(@project, :locale_id => locale.id) %>
    </li>
  <% end -%>
<% end %>

<% content_for :header do %>
  <h2><strong><%= @project.name %></strong></h2>
  <h4><%= @project.api_key %></h4>
  <%= render 'shared/locale_dropdown' %>
<% end %>

<% if @localizations.empty? -%>
  <div id='empty'>
    <h3>You haven&rsquo;t added any blurbs to your project yet.</h3>
    <p>Please follow the instructions below to add your first blurb, and refresh this page when you&rsquo;re ready.</p>
  </div>

  <%= render 'projects/installation_instructions', :project => @project %>
  <%= render 'blurbs/new_blurb_instructions', :project => @project %>
<% else -%>
  <div id='start_search'>
    <h3>Type the first few words of the text you&rsquo;d like to edit.</h3>
    <p>Results will show up as you type; so the more you type the more refined your results will be. </p>
  </div>

  <div id='blurb_search' class='start'>
    <fieldset class='inputs'>
      <label for='search_blurbs'>Search for the text you're looking to replace</label>
      <input type='text' id='search_blurbs' class='prefilled' />
    </fieldset>
  </div>

  <div id='no_results' style='display: none'>
    <h3>No results matched your search.</h3>
    <p>Try typing the first few words of the text you&rsquo;d like to edit.</p>
  </div>

  <ul class='blurbs-list'>
    <li>
    </li>
  </ul>

  <script type='text/template' id='blurbTemplate'>
    <a href='#'>
      <p></p>
      <h4 class='projectname'></h4>
    </a>
  </script>

  <div id='view_all'><a href='#'>View all <%= pluralize(@localizations.size, 'blurb') %></a></div>
  <div id='view_not_filled'><a href='#'>View Not Filled</a></div>

  <% content_for :javascript do -%>
    <script type='text/javascript'>
      $(document).ready(function () {
        var template = $('#blurbTemplate').html();
        $('.blurbs-list > li').incrementalSearch({
          blankSlate: '#start_search',
          items:
            <% cache :action_suffix => "#{@project.etag}_#{@locale.key}_json" do -%>
              <%= json @localizations %>,
            <% end -%>
          noResults: '#no_results',
          queryInput: '#search_blurbs',
          render: function (item) {
            var url = '/localizations/' + item.id + '/versions/new';
            var li = $('<li>').html(template);
              li.find('p').text(item.draft_content);
              li.find('h4').text(item.key);
              li.find('a').attr('href', url);
            return li;
          },
          search: ['key', 'draft_content'],
          searchContainter: '#blurb_search',
          viewAll: '#view_all a',
          viewNotFilled: '#view_not_filled a'
        });
      });
    </script>
  <% end -%>
<% end -%>