config/routes.rb
Copycopter::Application.routes.draw do
  namespace :api do
    namespace :v2 do
      resources :projects, :only => [] do
        resources :deploys, :only => [:create]
        resources :draft_blurbs, :only => [:create, :index]
        resources :published_blurbs, :only => [:index]
      end
    end
  end

  resources :projects, :only => [:index, :show] do
    resources :blurbs, :only => [:destroy]
    resources :locales, :only => [:new]
  end

  resources :localizations, :only => [] do
    resources :versions, :only => [:new, :create]
  end

  root :to => 'projects#index'
end

app/models/version.rb
class Version < ActiveRecord::Base
  # Attributes
  attr_accessible :content, :published

  # Associations
  belongs_to :localization

  # Validations
  validates_presence_of :localization_id

  # Callbacks
  before_validation :set_number, on: :create
  after_create :update_localization
  after_create :update_project_caches, :unless => :first_version?

  def revise(attributes = {})
    localization.
      versions.
      build self.attributes.merge('published' => published).merge(attributes)
  end

  def project
    localization.project
  end

  def published=(published)
    @publish_after_saving =
      ActiveRecord::ConnectionAdapters::Column::TRUE_VALUES.include?(published)
  end

  def published
    if new_record?
      publish_after_saving?
    else
      localization.published_version_id == id
    end
  end

  def published?
    published
  end

  private

  def publish_after_saving?
    @publish_after_saving
  end

  def set_number
    if !number && localization
      self.number = localization.next_version_number
    end
  end

  def update_localization
    unless first_version?
      localization.update_attributes! draft_content: content
    end

    if publish_after_saving?
      localization.publish
    end
  end

  def update_project_caches
    project.update_caches
  end

  def first_version?
    number == 1
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_filter :authorize

  def create
    self.set_html_preference params[:prefer_html]
    @localization = Localization.find(params[:localization_id])
    @version = @localization.revise(params[:version])
    @version.save!

    if @version.published?
      flash[:success] = 'Content published. ' +
        'It takes up to 5 minutes for new content to appear on the live site.'
    else
      flash[:success] = 'Draft saved.'
    end

    redirect_to new_localization_version_url(@localization)
  end

  def new
    @localization = Localization.find(params[:localization_id])
    @version = @localization.revise
    @project = @localization.project
    @locale = @project.locale(@localization.locale_id)
  end
end

app/views/versions/_form.html.erb
<%= form.inputs do %>
  <%= form.input :published, :as => :radio,
        :collection => [['Draft', false], ['Publish', true]],
        :wrapper_html => {
          :style => version.published? ? 'display: none' : ''
        } %>
  <% if version.published? %>
    <li class='published'>Published</li>
    <li class='explanation'><%= t 'blurb.published_html' %></li>
  <% elsif localization.published_content? %>
    <li class='explanation'><%= t 'blurb.draft_html' %></li>
  <% else %>
    <li class='explanation'><%= t 'blurb.first_draft_html' %></li>
  <% end %>

  <li class='published_version' style='display: none'>
    <pre><%= localization.published_content %></pre>
  </li>

  <%= form.input :content %>

  <li id='editor_mode'>
    <%= link_to 'Edit as HTML', '#', :id => 'edit_html' %>
    <%= link_to 'Edit in simple mode', '#', :id => 'edit_simple',
          :style => 'display: none' %>
  </li>
<% end %>

<%= hidden_field_tag 'prefer_html', prefer_html? %>

<% content_for :javascript do %>
  <script type='text/javascript'>
    $(function () {
      Editor.start({
        css: <%== Yajl::Encoder.encode(stylesheet_path('wysiwyg')) %>,

        <% if localization.published_content? %>
          draftExplanation: <%= raw Yajl::Encoder.encode(t('blurb.draft_html')) %>,
        <% else %>
          draftExplanation: <%= raw Yajl::Encoder.encode(t('blurb.first_draft_html')) %>,
        <% end %>

        <% if prefer_html? %>
          preferHtml: true,
        <% end -%>

        publishedExplanation: <%= raw Yajl::Encoder.encode(t('blurb.published_html')) %>
      });
    });
  </script>
<% end -%>

app/views/versions/new.html.erb
<% content_for :title, "Edit #{h @localization.key}" %>

<% content_for :locales do %>
  <% @localization.alternates.each do |localization| %>
    <li>
      <%= link_to localization.locale.key,
            new_localization_version_path(localization) %>
    </li>
  <% end -%>
<% end %>

<% content_for :header do %>
  <h2>
    <%= link_to @project.name, @project %>
    <span>&gt;</span>
    <strong><%=h @localization.key %></strong>
  </h2>

  <%= render 'shared/locale_dropdown', :locales => @project.locales %>
<% end -%>

<%= semantic_form_for [@localization, @version] do |form| %>
  <%= render 'form', :form => form, :version => @version,
        :localization => @localization %>

  <%= form.buttons do %>
    <%= form.commit_button 'Save Blurb' %>

    <%= link_to project_blurb_path(@project, @localization.blurb),
          :method => :delete,
          :data => { :confirm => 'Delete blurb?' },
          :id => 'remove_blurb' do %>
      <span class='delete_item'>Remove blurb</span>
    <% end -%>
  <% end %>
<% end -%>